"""Turn a model choice + dial into config Strix/Arès actually consumes.

Two artifacts are produced:

1. A derived Ollama model (`ares-<base>-<level>`) built from a Modelfile that
   BAKES IN the dial's `num_ctx`/`num_gpu`. Baking beats passing per-request
   options because it applies no matter how the agent framework forwards (or
   drops) options — the resource dial is then guaranteed, not best-effort.

2. An `ares.env` file exporting the variables Strix reads:
   STRIX_LLM, LLM_API_BASE, LLM_API_KEY (dummy for local), OLLAMA_NUM_PARALLEL,
   STRIX_REASONING_EFFORT, LLM_MAX_TOOL_CALLS_PER_TURN.
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

from .dial import EngineConfig

DEFAULT_CONFIG_DIR = Path.home() / ".ares"


def derived_model_name(base_tag: str, level: int) -> str:
    # e.g. "hf.co/OBLITERATUS/Qwen3.6-27B-OBLITERATED" -> "ares-qwen3-6-27b-obliterated-l90"
    base = base_tag.split("/")[-1].split(":")[0].lower()
    base = re.sub(r"[^a-z0-9]+", "-", base).strip("-")
    return f"ares-{base}-l{level}"


# Strix agent prompts are ~40k tokens; never build a model below this.
STRIX_CTX_FLOOR = 49152


def build_modelfile(base_tag: str, engine: EngineConfig) -> str:
    num_ctx = max(engine.num_ctx, STRIX_CTX_FLOOR)
    return (
        f"FROM {base_tag}\n"
        f"PARAMETER num_ctx {num_ctx}\n"
        f"PARAMETER num_gpu {engine.num_gpu}\n"
        "# Generated by `ares init`. Resource-dial level "
        f"{engine.level}, ctx floored to {STRIX_CTX_FLOOR} for Strix. Re-run `ares init` to change.\n"
    )


def create_derived_model(
    base_tag: str, engine: EngineConfig, *, config_dir: Path = DEFAULT_CONFIG_DIR
) -> str:
    """Write the Modelfile and run `ollama create`. Returns the derived name."""
    config_dir.mkdir(parents=True, exist_ok=True)
    name = derived_model_name(base_tag, engine.level)
    modelfile = config_dir / f"{name}.Modelfile"
    modelfile.write_text(build_modelfile(base_tag, engine), encoding="utf-8")
    proc = subprocess.run(
        ["ollama", "create", name, "-f", str(modelfile)],
        capture_output=True, text=True,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"ollama create failed: {proc.stderr.strip()}")
    return name


def build_env(model_slug: str, endpoint: str, engine: EngineConfig) -> dict[str, str]:
    """model_slug is the Strix STRIX_LLM value, e.g. 'ollama/ares-qwen3-6-l90'."""
    # Lessons baked in from the real run: OpenAI-compatible routing (litellm's
    # ollama_chat native path retry-storms), the /v1 endpoint, generous timeouts
    # (local models are slow on Strix's ~40k prompts), and the sandbox image.
    base = endpoint if endpoint.rstrip("/").endswith("/v1") else endpoint.rstrip("/") + "/v1"
    slug = model_slug.replace("ollama/", "openai/", 1) if model_slug.startswith("ollama/") else model_slug
    return {
        "STRIX_LLM": slug,
        "LLM_API_BASE": base,
        "LLM_API_KEY": "ollama-local",
        "OLLAMA_NUM_PARALLEL": str(engine.num_parallel),
        "STRIX_REASONING_EFFORT": engine.reasoning_effort,
        "LLM_MAX_TOOL_CALLS_PER_TURN": str(engine.max_tool_calls_per_turn),
        "STRIX_STREAM_IDLE_TIMEOUT": "1800",
        "LLM_TIMEOUT": "1800",
        "ARES_IMAGE": "ares-sandbox:1.3.0",
        # Arès is local-first & private: telemetry off by default (opt back in
        # by removing these). This also makes every generated profile air-gapped.
        "STRIX_TELEMETRY": "0",
        "DO_NOT_TRACK": "1",
    }


def render_env_file(env: dict[str, str]) -> str:
    lines = [
        "# Arès local engine config — generated by `ares init`.",
        "# Source it before running Arès:  source ares.env",
        "",
    ]
    lines += [f'export {k}="{v}"' for k, v in env.items()]
    return "\n".join(lines) + "\n"


def write_env_file(env: dict[str, str], path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_env_file(env), encoding="utf-8")
    return path
